package homework;

/*this is homework in 2018 6 4*/

public class homework{
    public static void main(String args[]){
        System.out.println("\n                                       Based on Python function: pillow" +
                "\n                                          code by Wyatt \"print Rick\"\n");
        System.out.println("\nrYJx}}}}}}}}}}}}}}}}{)xXJJJJJJJJJJJJJJJJJv){}1(fJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJUz|1}}}}}}}}}}}}}}}}}}}}}\\cJJJJJJJJJJJJJJJJJ\n" +
                "JYf1}}}}}}}}}}}}}}{uXJJJJJJJJJJJJJJJJJJJJJJJUJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJcr|{{}}}}}}}}}}}}}}}{JJJJJJJJJJJJJJJJJJJ\n" +
                "U1}}}}}}}}}}}}}}\\zUJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJXr)}}}}}}}}}}}}}}}jYJJJJJJJJJJJJJJJJJ\n" +
                "{}}}}}}}}}}}}{{tJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJcvvUJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJUx)}}}}}}}}}}}}}}{1|xUJJJJJJJJJJJz\n" +
                "}}}}}}}}}}}{}fUJJJJJJJJJJJJJJJJJJJJJJXj1{}}}1jjt{}}{}}}}{nzYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYx\\{{}}}{}}}}}}}}}}{(XJJJJJJJcr\n" +
                "}}}}}}}}}}1fcJJJJJJJJJJJJJJJJJJJJJJJY{}1X|}}}}}}}}}}}}}}}}}})\\fvXUJJJJJJJJJJJUcnrt\\\\/fUJJJJJJJJJJJUzu|{}}}}}}}}}}}}}}1/JJJJJJn\n" +
                "}}}}}}}}{tJJJJJJJJJJJJJJJJJJJJJJJJv)}}}pdc1}}}}}}}}}}}}}}}}}}}}}{{11111111{{}}}}}}}}}{)rJJJJJJJJJJJJJJUzvx|){}}}}}}}}})nUJJJJ\n" +
                "}}}}}{(UJJJJJJJJJJJJJJJJJJUUJJJJJJf{}}}}OX0bq{}}}}}}}}}}}}}}}}}}}}}}}}{}}}}}}}}}}}}}}}}}}rUJJJJwCJJJJJJJJJJJJJJUY)}}}}}}})JJJJ\n" +
                "1\\fuJJJJJJJJJJJJJJJJJJvt{}}}{{(jt)}}}}}}JqII1pU\\}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}{tJJmwpQUxnUJJJJJJJJJJJJJc1}}}}}(zJJ\n" +
                "JJJJJJJJJJJJJJJJJJJUn|}}}}}}}}}}}}}}}}}}nql;;<fZz)}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}\\wp>zdJJcrrnYJJJJJJJJJJJUv\\}}}}}|J\n" +
                "JJJJJJJJJJJJJJJJJJz{{}}}}}}}}}}}}}}}}}}}\\Oi;;;;lJdm}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}wd];!UQJJxjjrrxUJJJJJJJJJJJ|}}}}}f\n" +
                "JJJJJJJJJJJJJJJJc){}}}}}}}}}}}}}}}}}}}}}um[;;;;;;Ifwn{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}{{rw>;;;+dCJJcrjjjrrvJJJJJJJJJUx1}}}}\n" +
                "JJJJJJJJJJJJJJJc}{}}}}}}}}}}}}}}}}}{1fcJJ0XI;;;;;;;{0p(}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}{zpl;;;;;pmJJJUrjjrrrrcUJJJJJJJJX{}}}\n" +
                "JJJJJJJJJJJJJUt{}}}}}}}}}}}}}}}{(fXUJJJJJCp<;;;;;;;;I_pOr}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}Qw);;;;;;OdCJJJXxjjjjjrrXJJJJJJJJu1{}\n" +
                "JJJJJJJJJJJJJ1}}}}}zYu}}}}}}{1jUJJJJJJJJJJdn;;;;;;;;;;i|pv{}}{}}}}}}}}}}}}}}}}}}}}}}}}{}tC_;;;;;;;jdZJJJJUrrjjjjrruYJJJJJJJU\\}\n" +
                "JJJJJJJJJJJU|}}}}|YJJJ{}}}}}uUJJJJJJJJJJJJdZI;;;;;;;;;;;Iqqn}}}}}}}}}}}}}}}}}}}}}}}}}}{Xd!;;;;;;;;_dqJJJJJzrjjjjjjrrJJJJJJJJJ{\n" +
                "JJJJJJJJJJn1{}}{zJJJJJ\\{}}{/JJJJJJJJJJJJJJwb};;;;;;;;;;;;I(Z0JJz\\{}}}}}}}}}}}}}}}jr|{{qq(;;;;;;;;;!pdJJJJJXrjjjjjjjjXJJJJJJJJX\n" +
                "JJJJJJJJJz{}}{/zJJJJJJUvruYJJJJJJJJJJJJJJJrdY;;;;;;;;;;;;;;ILdmJUx}}}}}}}}}}}}(fvJJJc0xl;;;;;;;;;;;mdJJJJJujjjjjjjjrrUJJJJJJJJ\n" +
                "JJUcJJJJu)}}}XJJJJJJJJJJJJJJJJJJJJJJJJJJJU)qq;;;;;;;;;;;;;;;I_CwCu}}}}}}}{fXYUJJJJJJdUI;;;;;;;;;;;;LdJJJUnrjjjjjjjjjjuJJJJJJJJ\n" +
                "U){|JJJf}}{jUJJJJJJJJJJJJJJJJJJJJJJJJJJJJJzZd;;;;;;;;;;;;;;;;;;Ldz{}}}}}uUJJJJJJJJLp1I;;;;;;;;;;;;;CdJJJnjrrjjjjjjjjjrXJJJJJJJ\n" +
                "}}{jJJv{}{YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ0d;;;;;;;;;;;;;;;;;;I}Ox1}}})JJJJJJJJJZdc;;;;;;;;;;;;;;;QdJJJcrjjjjjjjjjjrrnJJJJJJJ\n" +
                "}1rUU/{{/XJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLbI;;;;;;;;;;;;;;;;;;;IOqv{}tJJJJJJJCZQ-;;;;;;;;;;;;;;;;wdJJJXrrjjjjjjjjjjrrJJJJJJJ\n" +
                "{YJJt{}uJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJdi;;;;;;;;;;;;;;;;;;;;l{wv{(JJJJJJZdO;;;;;;;;;;;;;;;;;!qdJJJUrrrjjjjjjjjjjjJJJJJJJ\n" +
                "UJJJ(}|JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJq_;;;;;;;;;;;;;;;;;;;;;;IpZtvJJzfxw}I;;;;;;;;;;;;;;;;;~dpJJJJxjrjjjjjjjjjjjUJJJJJJ\n" +
                "JJJJ(tJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJm};;;;;;;;;;;;;;;;;;;;;;;!np({}|0q!;;;;;;;;;;;;;;;;;;;}dwJJJJYrrjjjjjjjjjjjUJJJJJJ\n" +
                "JJJJUJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJZ1;;;;;;;;;;;;;;;;;;;;;;;;;_pYjpri;;;;;;;;;;;;;;;;;;;;ndOJJJJJJzvuxxrjrjjjjYJJJJYJ\n" +
                "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJZ1;;;;;;;;;;;;;;;;;;;;;;;;;;?Obi;;;;;;;;;;;;;;;;;;;;;;LbLJJJJJJJJJJJUrjjjjjUJJJJnJ\n" +
                "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJm};;;;;;;;;;;;;;;;;;;;;;;;;;;;I;;;;;;;;;;;;;;;;;;;;;;;qdJJJJJJJJJJJJJcrjrjrJJJJUrU\n" +
                "JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJq_;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;pwJJJJJJJJJJJJJXxrjrrJJJLUrX\n" +
                "JJJJJJJJJJJJJJJJzvvUJJJJJJJJJJJJJJJJJJJJJJJCd!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;dQJJJJJJJJJJJJJJXzC0wpwpwvrc\n" +
                "JJJJJJJJJJJJJUcnjjrxUJJJJJJJJJJJJJJJJJJJJJJQbI;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;>dJJCLOwqppddddpmCu}-~irpJxrc\n" +
                "JJJJJJJJJJJXnrjjjrjxJJJJJJJJJJJJJJJJJJJJJJJmd;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;)ddddOu]<!llIII;;;;;;;vdOXrjc\n" +
                "JJJJJJJJUzrrrrrrrrrXJJJJJJJJzurrrrrrjrrrrrnpw;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;Iuti;;;;;;;;;;;;;;;;;;ld0Jcrjz\n" +
                "JJJJJUXxrrxZbdwZQCJ00QLCCUvxrrrrrrrxxnuvzYZb/;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;+ZQJJnrrX\n" +
                "JJYcxrrjjrrxOri~-]}tncC0mqppddddddppwOLUx\\[-I;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;{wpJJJxrjX\n" +
                "Xrrjjjjjjrrrrdt;;;;;;;;;;;;IIIIIII;;;;;;;;;;;;;;;;;;;;;;;;;;;;I]\\zZwqppdddddddpppwZC}>;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;wpCJJJrjjX\n" +
                "jjjjrrjjjjjjjLq\\;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;![cddpLv|+>i!!!i!iii<}tUqbdddpppdddmLrilI;;;;;;;;;;;;;;;;;(0/UJJJrrjc\n" +
                "jjjjjjjjjjjrruLql;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;)cmCn)i!!!!!!!!!!i{fzpmLr|]!;;;;;;;;;;i_)YZpj]l;;;;;;;;;;;;I(m)}rJJJrjru\n" +
                "jjjjjjjjjjrxYJJ0n!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;<rZz1_!!!!!!!!!!!>c0qX(?I;;;;;;;;;;;;;;;;;;;;;l(Ld1I;;;;;;;;;;}wU}})JJJrjjr\n" +
                "jjjjjjjjjjuUJJJcpU!;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;~pX?!!!!!!!!!!!>Lqd\\>l;;;;;;;;;;;;;;;;;;;;;;;;;;;;lmm1;;;;;;;;;qmf}}{JJUrrjr\n" +
                "jjrjrrrrvYJJJJJcXpm;;;;;;;;;;;;;;;;;;;;;;;;;;;;;-md<!!!!!!!!!!ijwd(l;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ljqi;;;;;;;iqCf}}}JJYjjjj\n" +
                "jjrrrxcJJJJJJJJzrum|;;;;;;;;;;;;;;;;;;;;;;;;;;;+px>!!!!!!!!!}zpx+;;;;;;;!_{xY0pdpqqqpdqmQvt(_iI;;;;;;;;?m<;;;;;~wLJr}}}JJXjjjj\n" +
                "jjrjXJJJJJJJJJJJYUJdvl;;;;;;;;;;;;;;;;;;;;;;;I|m-!!!!!!!!!+nZ\\<;;;;;;]uQpLu}]+ii!!!!!i>~+[1tCwdLc\\I;;;;;qCI;;;~ZbJJv}}{JJXjjjj\n" +
                "jjjjcJJJJJJJJJJJJJJQdU;;;;;;;;;;;;;;;;;;;;;;;|pn!!!!!!!!!zdYI;;;;;?UqO/+i!!!!!!!!!!!!!!!!!!!!!i~{udpw}!;mdl;;;0dLJJX}{(JJzjjjj\n" +
                "jjjrrYJJJJJJJJJJJJJJLp-;;;;;;;;;;;;;;;;;;;;;;pn<!!!!!!!>zC+;;;;I-Jqx<!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!iJqpdbZI;;ld0JJJU}}rJJzjjjj\n" +
                "jjrjrzJJJJJJJJJJJJJJJCp/l;;;;;;;;;;;;;;;;;;;_X~!!!!!!!cdJ;;;;;-pQ\\!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!<Q?;I;;;luOJJJJJ{{YJJzrrjj\n" +
                "jjjrxUJJJJJJJJJJJJJJJXvpL;;;;;;;;;;;;;;;;;;!Z-!!!!!i>jC_;;;;jmp_i!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!iZc>;;;I/qCJJJJJ1tJJJzrrjj\n" +
                "jjrrUJJJJJJJJJJJJJJJu{}|m\\I;;;;;;;;;;;;;;;;nb!!!!!!-UqI;;;iuO[i!!!!!!!!!!!!!!!!!!!!!!!!!!!!!i!!!!!!!!jp1;;;;!\\bqLJJJ)zJJJzrjjj\n" +
                "rrrcJJJJJJJJJJJJJJJ/}}}}{dUl;;;;;;;;;;;;;;>qw!!!!!!wL-;;;tdQi!!!!i!!i!!!!!!!!!!!!!i!>}mdwLCX!!!!!!!!![QY;;;;;;!ndwLJ/YJJJzrjjj\n" +
                "rcUJJJJJJJJJJJJJJJu}}}}}}|ZOI;;;;;;;;;;;;;ndf!!!!!(zi;;!fL}i!+JYXXCJz}<!!!!!!!!!!i+rx?i!!!!!!!!!!!!!!>upI;;;;;;;;fQp0CJJJzrrjj\n" +
                "XJJJJJJJJJJJJJJJUt{}}}}}}}1zv>;;;;;;;;;;;;Zq~!!!!jdl;;xpO!!!!!!!!!!!i)XXi!!!!!!!!fL}!!!!!!!!!!!!!!!!!!{O!;;;;;;;;;;iXpdOCzrrjr\n" +
                "JJJJJJJJJJJJJJJJt{}}}}}}}}}{mm];;;;;;;;;;;qJi!!!)pL;I/m}i!!!!!!!!!!!!!i-v<i!!!ii!U>i!!!!!!!!!!!!!!!!!!~C>;;;;;;;;;;;;IiUpdOUur\n" +
                "JJJJJJJJJJJJJJJJ)}}}}}}}}}}}|ZbI;;;;;;;;;;pji!!!Ub?+Cd>!!!ii!!i!!!!!!!!!vC<!!!!iui!!!!!!!?|fjt1i!!!!!!iv)I;;;;;;;;;;;;;;;;(zwb\n" +
                "rXJJJJJJJJJJJJJJ{}}}}}}}}{\\zZx>;;;;;;;;;;Id?!!!!{QwCf~~}tOddqwqdpL(?>!!!!|[!!!i!!i!!_(qdmLUYYUCmpdj]>!!\\nI;;;;;;;;;;;;;;;;I_X0\n" +
                "rxUJJJJJJJJJJJJJ|{}}}}{\\cpZfI;;;;;;;;;;;;!q~!!!!!!!i{XpQzt|){}[]]{n0du-!!!!!!!!!!!<tpLjtttffjjrxxnCqp[i]Ql;;;;;;;;;;;;;;;!OdCr\n" +
                "jxYJJJJJJJJCL0OOOXvU0wdwu!;;;;;;;;;;;;;;;<m<!!!!!!iqqUft/|(){}[]?-+~~cp0i!!!!!!!!fpZ\\\\//ttffjjrxxxuucdC{di;;;;;;;;;;;;;>vpzrrr\n" +
                "rxUJJJJwdbbpOzuxxnn|_!;;;;;;;;;;;;;;;;;;;~Z>!!!!itdXrjft\\|(){}[]?_+~<i<xO-!!!!!i?dv(\\\\//tfffjjrxxxnuuzZbd+;;;;;;;;;;;;<bwLrjjr\n" +
                "ruJLppO(>I;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;_L>!!!!ZdCxrjtt/|(){}[]-_+~<i!iXdv!!!ird()(|\\//tfffjjrxxxnuuvcLb];;;;;;;;;;\\wpJJJrjjj\n" +
                "jUpw?l;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;?J>!!i/mzuxrjtt/|(){}[]-_+~<i!i<|q_!!upX1)(|\\//tfffjjrxxxnuuvccpw>;;;;;;;<nZzrrxnrjjj\n" +
                "jCwdOx~;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;?Ji!i|wzvuxrjft/|(){}[]-_+~<i!i<<}Z~!mC)1)(|\\//ttffjjrxxxnuuvvcCbC;;;;;;|qqxrrrjjjjjj\n" +
                "rXJJLwdZ1I;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;?Ji!-Cqcvuxrjft/|(){}[]-_+~<i!i<<~dv<d/{1)(|\\//tfffjjrxxxnuuvvczwd;;;;;IdOJxrrjjjjjjj\n" +
                "rUJJJJJQqd)i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;_Li!|pQcvuxrjft/|(){}[]?_+~<i!i<<~Q0|0(}1)(|\\/xLrffjjrxxxnuuvvczLb;;;;+wLJJrjjjjjjjjj\n" +
                "jUJJJJJJJJwdLI;;;;;;;;;;;;;;;;;;;;;;;;;;;~O>!npJcvuxrjft/|(){}[]]nQ]<i!i<<~xwuC)}1)(|\\/vmxffjjrxxxnuuvcczCb;;;iZdJJzrrjjjjjjjj\n" +
                "rJJJJJJJJJJJ0qx!;;;;;;;;;;;;;;;;;;;;;;;;;<Z<!vpJcvuxrjft/|(){}[]?)t+<i!i<<+tqnm(}1)(|\\//tfffjjrxxxnuuvccz0d;;;<ZbJYnjjrjjjjjjj\n" +
                "rJJJJJJJJJJJJLpd]I;;;;;;;;;;;;;;;;;;;;;;;>w<!npJcvuxrjft/|(){}[]-_+~<i!i<<~xw\\dj{1)(|\\//tfffjjrxxxnuuvcczpd;;;;Izmcrrjjjjjjjjj\n" +
                "jJJJJJJJJJJJJJJCqdq?!;;;;;;;;;;;;;;;;;;;;!q~!(pQcvuxrjft/|(){}[]-_+~<i!i<<~00?Qw|1)(|\\//tfffjjrxxxnuuvccObr;;;;;;mmcjrrjjjjjjj\n" +
                "rJJJJJJJJJJJJJJJJJLwdZ(<I;;;;;;;;;;;;;;;;Id_!_Upcvuxrjft/|(){}[]-_+~<i!i<~+dni{mm))(\\\\//tfffjjrxxxnuuvccdu;;;;;;;ixqurjjjjjjjj\n" +
                "cJJJJJJJJJJJJJJJJJJJJUOdpCt+;;;;;;;;;;;;;;b?i!1Ozvuxrjft/|(){}[]-_+~<i!i<~|Q>!!?Zu)(\\\\//tfffjjrxxxnuuvXmb[;;;;;;;;;+dOxrjrjjjj\n" +
                "JJJJJJJJJJJJJJJJJJJJJYxYJQwddu!;;;;;;;;;;;d(i!!(qcuxrjft/|(){}[]-_+~<i!i<tp>!!!<~bOt\\\\//tfffjjrxxxuuuCdZd];;;;;;;;;;~Qburjjjjj\n" +
                "JJJJJJJJJJJJJJJJJJJJJJrxUJCm|l;;;;;;;;;;;;pxi!!!0dCxrjtt/|(){}[]-_+~<iiiJpu!!!!~U_Xpn//ttfffjjrxxnucCZ|<d-;;;;;;;;;;;;lwwYrrrr\n" +
                "JJJJJJJJJJJJJJJJJJJJJJxrr0pC;;;;;;;;;;;;;;qXi!!!i(ZJxjf//|(){}[]-_+~<i-cX-i!!!!!!m}~CpCcrfffjrrncCdwui!>d+;;;;;;;;;;;;;l[XmJnr\n" +
                "JJJJJJJJJJJJJJJJJJJJJJcrudrl;;;;;;;;;;;;;;wLi!!!!!i0dOft/|(){}[]?_+~~Opci!!!!!!!!}0?!<(Ywppqqppp0r~i!!!<d<;;;;;;;;;;;;;;;I0b0r\n" +
                "JJJJJJJJJJJJJJJJJJJJJJJmdi;;;;;;;;;;;;;;;;wZi!!!!!!!+xbpQ\\(){}[]?}Qpb)>!!!!!!!!!!ixu!+!!!iii>>>i!!!!!!!<d+I;;;;;;;;;;;;_Yp0nrr\n" +
                "rvYJJJJJJJJJJJJJJJJJJCdQ_;;;;;;;;;;;;;;;;;Zp~!!!!!!!!ii_tZwqdppqm0)<!!!!!!>(!!!!!!]J!_L?i!!!!!!!!!!!i>!<C0qt!;;;;;;;+rwqJxrjjr\n" +
                "jjrxJJJJJJJJJJJJJJJCmp-I;;;;;;;;;;;;;;;;;;Cb]!!!!!!!!!!!!!!!!!!!!!ii}t!!!!!Yi!!!!!+z!!<fL_!!!!!!!!>\\L~!<|i!Um(;;;]nOwOLurrjjjj\n" +
                "jjrrXJJJJJJJJJJJJJQdY~;;;;;;;;;;;;;;;;;;;;Udt!!!!!!j<!!!!!!!!!!!!ivO/!!!!!!m+!!!!!~vi!!!iuQz~i!>]xU}>!!>ti!>npi\\QpOLJJJrrjjjjj\n" +
                "jjrjxUJJJJJJJJJJZdb!;;;;;;;;;;;;;;;;;;;;(ZCz0!!!!!!{QJi!!!!!!!i~rZ_i!!!!!!!Jr!!!!!+z!!!!!!i>|ncj[<!!!!!ifi!!+JbpQJJJJJXjjjrjjj\n" +
                "jjrjrcJJJJJJJJLw0[I;;;;;;;;;;;;;;;;;;;;-m\\!(m!!!!!!!!>JZL|11rJZj+!!!!!!!!!!}L+!!!!]J!!!!!!!!!!!!!!!!!!!>fi!!izLJJJJJJzrjjjjrrr\n" +
                "jjjrjrcJJJJJQddC->I;;;;;;;;;;;;;;;;;;;(p~!!]q!!!!!!!!!!!!<~~i!!!!!!!!!!!!!!>xu!!!iun!!!!!!!!!!!!!!!!!!!>\\i!!izLJJJJJvrjrrxzXUJ\n" +
                "jjjjjrrUJJJJLLQOqddwOL|-l;;;;;;;;;;;;{dz!!!+qi!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!+c~!!xJ<!!!!!!!!!!!!!!!!!!!<)i!!~Jbp0JJXrjjxzJJJJJ\n" +
                "jjjjjjjrxnnxrrxcJJJJJCmpbpwU>I;;;;;;;Zp-!!!!0i!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!>ZXUri!!!!!!!!!!!!!!!!!!!!-]!!!|m>jd0crrrrzJJJJJJ\n" +
                "jjjjjjjjjjjjjjrjXJJJJJJJJJC0qdbc]i;;;dZi!!!!ni!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ii<+?1|trjt}?+>i\\>!)+!!]LQ;;;qmcrjjJJJJJJJ\n" +
                "jjjjjjjjjjjjjrjjxYJJJJJJJJJJurrzOw;;;pZi!!!![~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!i1jzpbbpbbbbbbbbbbbwCJUC~!imY+;;;!tmvrrJJJJJJJ\n" +
                "rjrjjjjjjjjjjrjjrcJJJJJJJJJJXxrrQO;;;Qp]!!!!<(!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!i>zOpbbdx{i?bbbbbbbbbbbbbpJ|OZp{l;;;!<i~pOxJJJJJJJ\n" +
                "JUurrrjjjjjjjjjjjrYJJJJJJJJJJcrrpJ;;;[bU!!!!iu!!!!!!!!!!!!!!!!!!!!!!!!!!!i!|ZdbbbwbCII~wbbbbbbbbbbbbbbbp>/d!-YdbdppdbbbJJJJJJJ\n" +
                "JJUujjjjjjjjjjjjrrnJJJJJJJJJJJzXdr;;;;\\p>!!!!J-!!!!!!!!!!!!!!!!!!!!!!!!!-vpbbp[lItbbwpbbbbbbbbbbbbbbbbbb_!}uI~bUrxucJJLZCJJJJJ\n" +
                "JJUvjjjjjjjjjjjjrrrJJJJJJJJJJJJpZ>;;;;;[Q)!!!z/i!!!!!!!!!!!!!!!!!!!!![x0bbbdziIl_dbbbbbbbdLnJbbbwCdbbbbb\\iiQ?;ndZJJJJJJJJJJJJJ\n" +
                "JJUvjrjjjjjjjjjjjrrvJJJJJJJJJJCb[;;;;;;;\\mU|~tX_!!!!!!!!!!!!!!!!!![c0bdO1-jbbqOqbbbp/rbbb+IIiqb]lIUbbbbb{iiQ-;l0bJJJJJJJJJJJJJ\n" +
                "JJJvjrjjjjjjjjjjjjjrvJJJJJJJJJp1;;;;;;;;;I(Upbp1!!!!!!!!!!!!!!!+umbbb?lII+wbbbbbbdjlIIUbdQ0Ombbpqqbbbbbb|i{uI;;ubJJJJJJJJJJJJJ\n" +
                "JJJvjrjjjjjjjjjjjjjjrvJJJJJJQpp;;;;;;;;;;;;II]Zz!!!!!!!!!!ii]uqdwY!I/m\\)OdbdJ?(mb)<}0pppqQJXcuxft/|()?~i>fbJLwbddJJJJJJJJJJJJJ\n" +
                "JJJzrrjjjjjjjjjjjjjjjrYJJJJJpddpwZCJUYYUQOpddlrpi!!!!!!!ijJpx|pIIII_qbbbbbb~Il1vmdx{i!!!!!!!!!!!!!!!!i~)pp0LLCJJJJJJJJJJJJJJJJ\n" +
                "JJJUrrjjjjjjjjjjjjjjjrxzJJJJJJJJJCCCLLLCCCzvdl~C_!!<+i>rmdz?I<p!IIfwbbbbbbp(UY_!IZ\\!!!!!!!!!!!!}vXUUJqdqCJJJJJJJJJJJJJJJJJJJJJ\n" +
                "JJJJxjjjjjjjjjjjjjjjjrrjnJJJJJJJJJJJJJJJJJJJq-;1J>!Q|iqbb!III(ddddbbbbbbbbp~l;;;;0t!!!!!!!!!!!!!!!!!~wCJJJJJJJJJJJJJJJJJJJJJJU\n" +
                "JJJJcrjjjjjjjjjjjjjjjrjjrvUJJJJJJJJJJJJJJJJJm1;;pu|]~Xbbb(l!Jdbbbbbbbbbdf!;;;;;;;p]!!!!!!!!!!!!!!!!!xOJJJJJJJJJJJJJJJJJJJJUx)}\n" +
                "JJJJJzrrrrjjjjjjjjjjjjjjrrrcJJJJJJJJJJJJJJJJm{;;Cdz~cbbbbbbbbbbbbbbbb0t>;;;-u|Ii)/!!!!!!!!!!!!!!!!!{dJJJJJJJJJJJJJJJJJJJzf}}}}\n" +
                "UJJJJJUrrrjjjjjjjjjjjjjjjrrrcUJJJJJJJJJJJJJJp<;;qCi(pbbbbbbbbbbbbbbbt;;>;;;m?[nj}!!!!!!!!!!!!!!!!!?qdJJJJJJJJJJJJJJJJJU({}}}}}\n" +
                "X|XJJJJUurrrjjjjjjjjjjjjjjjjrrvJJJJJJJJJJJJQbI+Ub[!/dbbbbbbbbbbbbOCp}<Up;;l/!!!!!!!!!!!!!!!!!!!!!!mbCJJJJJJJJJJJJJJJz|{}}}}}}}\n" +
                "X}(cJJJJJUrrrjjjjjjjjjjjjjjjrrrxYJJJJJJJJJJpbbdp0<!)pbbbbbbbbbdt>i!1Zu]X;;?<!!!!!!!!!!!!!!!!!!!!!-bLJJJJJJJJJJJJJJUr}{{}}}}}}}\n" +
                "z}}(JJJJJJJUcxrjrjjjrrrrrjjjjjrrjxUJJJJJJJJJJJJLL>!>jqbbbbbwj?_!!!!!!!-Y;;ti!!!!!!!!!!!!!!!!!!!i|mCJJJJJJJJJJJJXu1}}}}}}}}}}}}\n" +
                "c}}}zJJJJJJJJJJUXzzczXYYXurjjrjjrjruXJJJJJJJJJJJd?!!!_LpC}+<JU(!!!!!!![U;;n!!!!!!!!!!!!!!!!!!!!vpZJJJJJJJJJJcf{}}}}}}}}}}}}}1z\n" +
                "c}}}(UJJJJJJJJJJJJJJJJJJJJJUnrrrjjjrruUJJJJJJJJJdq[!!!!!!{LJ>!!!!!!!!!{U;;v!!!!!!!!!!!!!!!!!!!{pQJJJJYcut(){}}}}}}}}}}}}}}nYJJ\n" +
                "c}}}}tUJJJJJJJJJJJJJJJJJJJJJJJJvxrrjrrrrXUJJJJJJJwbCf\\zmdbL}!!!!!!!!!!(z;;v!!!!!!!!!!!!!!!!!(qbJYv{{{}}}}}}}}}}}}}}}}{}/cJJJUc\n" +
                "z}}}}}jJJJJJJJJJJJJJJJJJJJJJJJJJJJJUYcccczJJJJJJJJJQOOQCJJLOOr{i!!!!!itn;;v!!!!!!!!!!!!!!+|LqLn{}}}}}}}}}}}}}{|tjzUUJJJJUc{}{}\n" +
                "Y}}}}}{JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJUXcf/|{}}\\nQwLv_i!>xr{}ci!!!!!!!!ii-tYdw0|{{{}}}}}}}}}}}jcYJJJJJJJJY/){}}}{\n" +
                "J}}}}}{rJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJu}}}}}}}}}}}}1|nqdpwpOfQZ?-__?[/vJqpdm0JY/}{}}}}}}}}}}1uUJJJJJJJXx){}}}{)\\fj\n" +
                "J}}}}}}{fUJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYx{{}}}}{{{tvUJJJJC0ZwqpppppqmOQJJJJJc(}}{}}}}}}}}{tJJJJJJJJJ}}}{|frrjjrjr\n" +
                "J{}}}}}}}|UJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJYzu{}}}}}}}}}}}fXJJJJJJJJJJYXXUJJYurjjjj\n" +
                "Jj}}}}}}}}\\zJJJJJJJJJJJJJJJJUzXJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJXxt){}}}}}}}}}}}}{1xJJJJJJJJJJJJJJJJJJJXxjjjj\n");
    }
}